server:
  port: 8082
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yarlung-zangbo/Yuesheng-Audio-Book
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
